### ISSUE TITLE
ciでStorybookのビルドと、GitHub Pages等でホスティング

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/ToyBox-frontend#5]
## わざわざ環境構築しなくてもStorybookが見れる状態にしたいので、ciでビルドできるようにしたい！
- GitHub Actions（Privateレポジトリだと有料。。。）
- CircleCI
- などを用いて、自動でビルドできるようにし、GitHub PagesやNetlify等でホスティングすることで誰でも見られて嬉しい。

**Comment by citrus-candy** [comment]
Netlifyでデプロイしました
- https://toybox-c3.netlify.app/
- https://toybox-c3-storybook.netlify.app/
