### ISSUE TITLE
packageの更新通知、更新を自動化したい

### ISSUE THREAD

**Issue by Simo-C3** [Kyutech-C3/ToyBox-frontend#50]
バイト先でdependabotというパッケージ更新自動化ツールを使う機会があり、とても便利だったので導入したい
導入方法は簡単です

**Comment by citrus-candy** [comment]
https://zenn.dev/dzeyelid/articles/e36d439cdeda5edb7ddc

**Comment by citrus-candy** [comment]
https://github.com/Kyutech-C3/ToyBox-frontend/security/dependabot
一応ここで脆弱性のアラートは出てる

**Comment by Simo-C3** [comment]
とりあえずこれで十分ですね
