### ISSUE TITLE
タグ選択を前方一致検索でやりたい

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/ToyBox-frontend#54]
**どんな機能を追加したい？**
- タグ選択をテキスト入力からの前方一致検索で実現したい。

**機能追加にて解決したい問題は？**
- 閲覧時・Work作成時、既存のタグ選択モーダルでは、タグが増えたときの一覧性が悪く、見たい/つけたいタグを選択するのが大変。

**どのようなどうやって実装（解決）する？**
- タグが並ぶ領域の右端にテキストボックス（縁無し）を配置
- テキストボックスにて文字を入力すると、その文字列と前方一致するタグを探してカーソル（キャレット）の下にサジェストウィンドウを表示する。
![image](https://user-images.githubusercontent.com/12907598/170256608-714b5bab-5e2d-4fba-b713-be4e14e78090.png)
  - サジェストウィンドウの候補からクリック or Tab+Enterで選択する
  - そもそもサジェストを無視して文字列入力→スペース入力でその文字列と完全一致のタグを選択 or なければタグの作成からの選択が走る
- 選択されたら左側にタグが追加されて、フォーカスは右端のテキストボックス。

- タグについては、初期化時にFetchしてVuexストアへ全て保持しておき、前方一致検索は`Array.prototype.filter()`と`Array.prototype.startsWith()`を使ってVuexのActionとして実装したい。

**ほかに解決策はある？**
- タグがめっちゃ多くなってしまって、初期化時Fetchがおそすぎてアプリのロードを引っ張るほどになるなら、キー入力毎にAPIに問い合わせてもいいよね
  - Qiitaの記事編集画面のタグがそうだった
  ![image](https://user-images.githubusercontent.com/12907598/170257040-100bf0e6-d676-4fe2-a990-eb8f67331cc7.png)

- 今のタグ選択モーダルに前方一致検索機能を追加する。
  - モーダルに検索窓を設けて絞り込みを行い、その結果から選択する。
  - 

**そのほか、知ってほしい情報などのメモ**

**Comment by Simo-C3** [comment]
前方一致検索いいですね！！qiitaのタグとかもそんな感じですし
あと、モーダルでのタグの表示方法ですが、タグにコミュニティー属性の付与が可能になっているのでカテゴライズして表示するのもありですね。

少し話は違いますが、作品に付けられるタグ数と検索の際に選択できるタグ数は制限を設けてもいいかもですね

**Comment by Simo-C3** [comment]
バックエンドにてタグの前方一致検索の機能実装を行い次第対応
