### ISSUE TITLE
作品投稿時の処理の分岐

### ISSUE THREAD

**Issue by Simo-C3** [Kyutech-C3/ToyBox-frontend#57]
**どんな機能を追加したい？**

- 作品投稿に成功した場合は作品詳細ページにリダイレクトする
- 作品投稿に失敗した場合は適切なエラー表示を行う

**機能追加にて解決したい問題は？**

- 投稿ボタンを押しても何の変化もないため、投稿が出来たかどうかがわからない。

**どのようなどうやって実装（解決）する？**

- 投稿ボ処理が完了後にリダイレクト処理を行う。

**ほかに解決策はある？**

- ない

**そのほか、知ってほしい情報などのメモ**

**Comment by rkun123** [comment]
POST成功後のリダイレクトならミドルウェアを使う必要はなさそう
ミドルウェアはページアクセスして表示する前に実行されるものだったはずなので...
https://qiita.com/yama-t/items/97871a4c2f1cd8325078#%E6%A6%82%E8%A6%81

**Comment by Simo-C3** [comment]
作品投稿に成功した場合はサイトTopにリダイレクトするように実装
